frequency: 5m
components:
  - component_slug: "errata-reliability"
    sub_component_slug: "mcp-server"
    http_monitor:
      url: "http://10.0.76.71:8000/health"
      code: 200
      retry_after: 5s
      severity: "Down"
  - component_slug: "errata-reliability"
    sub_component_slug: "slack-bot"
    systemd_monitor:
      unit: "oar-bot.service"
      severity: "Down"
  - component_slug: "errata-reliability"
    sub_component_slug: "release-progress-dashboard"
    systemd_monitor:
      unit: "release-progress-dashboard.service"
      severity: "Down"
