frequency: 5m
components:
  - component_slug: "errata-reliability"
    sub_component_slug: "mcp-server"
    http_monitor:
      url: "http://localhost:8000/health" #Use localhost because component-monitor and mcp-server runs on the same server
      code: 200
      retry_after: 5s
      severity: "Down"
  - component_slug: "errata-reliability"
    sub_component_slug: "slack-bot"
    systemd_monitor:
      unit: "oar-bot.service"
      severity: "Down"
  - component_slug: "errata-reliability"
    sub_component_slug: "release-progress-dashboard"
    systemd_monitor:
      unit: "release-progress-dashboard.service"
      severity: "Down"
