import sys

if sys.version_info < (3, 8):
    sys.exit("Sorry, Python < 3.8 is no longer supported.")


def version() -> str:
    """Get the package version, trying these sources in order:
    1. Defined version from pyproject.toml (via importlib.metadata)
    2. _version.py (generated by setuptools_scm)
    3. Directly from setuptools_scm
    
    Returns:
        str: The package version string
    """
    try:
        from importlib.metadata import version as pkg_version
        return pkg_version("oar")
    except ImportError:
        try:
            from ._version import version
            return version
        except ModuleNotFoundError:
            from setuptools_scm import get_version  # type: ignore[import-not-found]
            return get_version()
