# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev88+g7c2e2bc.d20230720'
__version_tuple__ = version_tuple = (0, 1, 'dev88', 'g7c2e2bc.d20230720')
