FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.21-openshift-4.16
LABEL maintainer="jiazha@redhat.com"
WORKDIR /go/src/github.com/k8sgpt-ai
RUN git clone --branch main https://github.com/k8sgpt-ai/k8sgpt.git && \
    cd k8sgpt && \
    go mod vendor && \
    make build
RUN cp ./k8sgpt/bin/k8sgpt /usr/bin/
ENTRYPOINT ["k8sgpt"]

