FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.20-openshift-4.14
LABEL maintainer="jiazha@redhat.com"
WORKDIR /go/src/github.com/k8sgpt-ai
RUN git clone https://github.com/k8sgpt-ai/k8sgpt.git && \
    cd k8sgpt && \
    go mod vendor && \
    make build
ENTRYPOINT ["./k8sgpt/bin/k8sgpt"]

